/*
 * Copyright © 2011 James Simmons 
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * Authors:
 *	James Simmons <jsimmons@infradead.org>
 */

#include "drmP.h"
#include "drm.h"
#include "drm_crtc.h"
#include "drm_crtc_helper.h"

#include "via_drv.h"

/*
 * Routines for controlling stuff on the analog port
 */
static const struct drm_encoder_funcs via_analog_enc_funcs = {
	.destroy = drm_encoder_cleanup,
};

/* Manage the power state of the DAC */
static void
via_analog_dpms(struct drm_encoder *encoder, int mode)
{
	struct drm_crtc *crtc = encoder->crtc;
	u8 dacmode, mask = BIT(4) + BIT(5), path = BIT(6);
	struct drm_via_private *dev_priv;
	struct via_crtc *iga;	
	void __iomem *regs;

	dev_priv = encoder->dev->dev_private;
	//regs = dev_priv->mmio.virtual + 0x83C0;
	regs = ioport_map(0x3c0, 100);

	/* Select the proper IGA */
	//iga = container_of(crtc, struct via_crtc, base);
	//if (iga->iga1) path = 0;
	path = 0;
	seq_iowrite8(regs, 0x16, path); 

	dacmode = crtc_ioread8(regs, 0x36);
	switch (mode) {
	case DRM_MODE_DPMS_SUSPEND:
		dacmode |= BIT(5);	// VSync off  
		break;
	case DRM_MODE_DPMS_STANDBY:
		dacmode |= BIT(4);	// HSync off	
		break;
	case DRM_MODE_DPMS_OFF:
		dacmode |= mask;	// HSync and VSync off
		break;
	case DRM_MODE_DPMS_ON:
	default:
		dacmode &= ~mask;
		break;
	}

	crtc_iowrite8(regs, 0x36, (dacmode & mask));
}

/* Pass our mode to the connectors and the CRTC to give them a chance to
 * adjust it according to limitations or connector properties, and also
 * a chance to reject the mode entirely. Usefule for things like scaling.
 */
static bool
via_analog_mode_fixup(struct drm_encoder *encoder,
		 struct drm_display_mode *mode,
		 struct drm_display_mode *adjusted_mode)
{
	drm_mode_set_crtcinfo(adjusted_mode, 0);
	return true;
}

static void
via_analog_prepare(struct drm_encoder *encoder)
{
	via_analog_dpms(encoder, DRM_MODE_DPMS_OFF);
}

static void
via_analog_commit(struct drm_encoder *encoder)
{
	via_analog_dpms(encoder, DRM_MODE_DPMS_ON);
}

static void
via_analog_mode_set(struct drm_encoder *encoder,
		       struct drm_display_mode *mode,
		       struct drm_display_mode *adjusted_mode)
{
}

static const struct drm_encoder_helper_funcs via_analog_enc_helper_funcs = {
	.dpms = via_analog_dpms,
	.mode_fixup = via_analog_mode_fixup,
	.prepare = via_analog_prepare,
	.commit = via_analog_commit,
	.mode_set = via_analog_mode_set,
};

static enum drm_connector_status
via_analog_detect(struct drm_connector *connector, bool force)
{
	struct drm_device *dev = connector->dev;
	struct drm_via_private *dev_priv = dev->dev_private;
	struct via_i2c *i2c = dev_priv->i2c_par;
	struct i2c_adapter *adapter = NULL;
	struct edid *edid = NULL;

	drm_mode_connector_update_edid_property(connector, edid);

	adapter = &i2c->adapter;
	if (adapter) {
		edid = drm_get_edid(connector, adapter);
		if (edid) {
			drm_mode_connector_update_edid_property(connector, edid);
			kfree(edid);
			return connector_status_connected;
		}
	}
	return connector_status_unknown;
}

static void
via_analog_destroy(struct drm_connector *connector)
{
	drm_sysfs_connector_remove(connector);
	drm_connector_cleanup(connector);
	kfree(connector);
}

static int
via_analog_set_property(struct drm_connector *connector,
		  struct drm_property *property,
		  uint64_t value)
{
	struct drm_device *dev = connector->dev;

	if (property == dev->mode_config.dpms_property && connector->encoder)
		via_analog_dpms(connector->encoder, (uint32_t)(value & 0xf));
	return 0;
}

static const struct drm_connector_funcs via_analog_connector_funcs = {
	.detect = via_analog_detect,
	.fill_modes = drm_helper_probe_single_connector_modes,
	.destroy = via_analog_destroy,
	.set_property = via_analog_set_property,
};

/* This function test if the drm_display_modes generated by a display
 * monitor that is connected is supported by the graphics card.
 */
static int
via_analog_mode_valid(struct drm_connector *connector,
			struct drm_display_mode *mode)
{
	//struct drm_device *dev = connector->dev;

	if ((mode->flags & DRM_MODE_FLAG_INTERLACE) &&
	    !connector->interlace_allowed)
		return MODE_NO_INTERLACE;

	return MODE_OK;
}

static struct drm_encoder* 
via_best_encoder(struct drm_connector *connector)
{
	int enc_id = connector->encoder_ids[0];
	struct drm_encoder *encoder = NULL;
	struct drm_mode_object *obj;

	/* pick the encoder ids */
	if (enc_id) {
		obj = drm_mode_object_find(connector->dev, enc_id, DRM_MODE_OBJECT_ENCODER);
		if (!obj)
			return NULL;
		encoder = obj_to_encoder(obj);
	}
	return encoder;	
}

static const struct drm_connector_helper_funcs via_analog_connector_helper_funcs = {
	.mode_valid = via_analog_mode_valid,
	.get_modes = via_get_edid_modes,
	.best_encoder = via_best_encoder,
};

void via_analog_init(struct drm_device *dev)
{
	struct drm_connector *connector;
	struct drm_encoder *enc;
	void *par;
	int size;

	size = sizeof(struct drm_encoder) + sizeof(struct drm_connector);
	par = kzalloc(size, GFP_KERNEL);
	if (!par) {
		DRM_ERROR("Failed to allocate connector and encoder\n");
		return;
	}
	connector = par + sizeof(struct drm_encoder);
	enc = par;

	/* Piece together our connector */
	drm_connector_init(dev, connector, &via_analog_connector_funcs,
				DRM_MODE_CONNECTOR_VGA);
	drm_connector_helper_add(connector, &via_analog_connector_helper_funcs);

	connector->interlace_allowed = true;
	connector->doublescan_allowed = true;

	/* Setup the encoders and attach them */
	drm_encoder_init(dev, enc, &via_analog_enc_funcs, DRM_MODE_ENCODER_DAC);
	drm_encoder_helper_add(enc, &via_analog_enc_helper_funcs);
	enc->possible_clones = 1; //clone_mask;
	enc->possible_crtcs = 1; //crtc_mask;

	drm_mode_connector_attach_encoder(connector, enc);

	drm_sysfs_connector_add(connector);
}
